# This is a basic workflow to help you get started with Actions

name: gcc

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir ~/project
          echo -e "\033[32m----------- build gcc ----------\033[0m"
          cd ~/project
          sudo apt-get update
          sudo apt-get install -y git g++ libmpc-dev make flex
          git clone https://github.com/gcc-mirror/gcc.git
          cd gcc
          mkdir build
          cd build
          ../configure --disable-multilib
          time make -j$(nproc)

          cd ~/project
          rm -rf ~/project/gcc
          gcc_version='12.3.0'
          curl -L -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${gcc_version}.tar.gz
          tar -zxf gcc-${gcc_version}.tar.gz
          rm gcc-${gcc_version}.tar.gz
          cd gcc-releases-gcc-${gcc_version}
          mkdir build
          cd build
          ../configure --disable-multilib
          time make -j$(nproc)
