name: gcc

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # gcc-master-make:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: gcc master make
  #       run: |
  #         echo -e "\033[32m--------------- gcc master make ---------------\033[0m" > ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo "start: $(date)" >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo "system info:" >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo pwd: $(pwd) >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo lscpu: >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo core num: $(nproc) >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         lscpu >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo free -h: >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         free -h >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo df -h: >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         df -h >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo uname -a: >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         uname -a >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo lsb_release -a: >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         lsb_release -a >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         sudo apt-get update
  #         sudo apt-get install -y git g++ libmpc-dev make flex
  #         git clone https://github.com/gcc-mirror/gcc.git
  #         cd gcc
  #         mkdir build
  #         cd build
  #         ../configure --disable-multilib
  #         (time make 2>/dev/null) 2>> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         du -sh .. >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         df -h >> ${GITHUB_WORKSPACE}/gcc-master-make.log
  #         echo "end: $(date)" >> ${GITHUB_WORKSPACE}/gcc-master-make.log

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: gcc-master-make
  #         path: ${{ github.workspace }}/gcc-master-make.log

  gcc-master-make-j:
    runs-on: ubuntu-latest
    steps:
      - name: gcc master make -j$(nproc)
        run: |
          echo -e "\033[32m--------------- gcc master make -j$(nproc) ---------------\033[0m" > ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo "start: $(date)" >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo "system info:" >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo pwd: $(pwd) >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo lscpu: >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo core num: $(nproc) >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          lscpu >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo free -h: >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          free -h >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo df -h: >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo uname -a: >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          uname -a >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo lsb_release -a: >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          lsb_release -a >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          sudo apt-get update
          sudo apt-get install -y git g++ libmpc-dev make flex
          git clone https://github.com/gcc-mirror/gcc.git
          cd gcc
          mkdir build
          cd build
          ../configure --disable-multilib
          (time make -j$(nproc) 2>/dev/null) 2>> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          du -sh .. >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log
          echo "end: $(date)" >> ${GITHUB_WORKSPACE}/gcc-master-make-j.log

      - uses: actions/upload-artifact@v4
        with:
          name: gcc-master-make-j
          path: ${{ github.workspace }}/gcc-master-make-j.log

  gcc-12-3-0-make:
    runs-on: ubuntu-latest
    steps:
      - name: gcc 12.3.0 make
        run: |
          gcc_version='12.3.0'
          echo -e "\033[32m--------------- gcc-${gcc_version} make ---------------\033[0m" > ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo "start: $(date)" >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo "system info:" >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo pwd: $(pwd) >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo lscpu: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo core num: $(nproc) >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          lscpu >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo free -h: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          free -h >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo df -h: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo uname -a: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          uname -a >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo lsb_release -a: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          lsb_release -a >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          sudo apt-get update
          sudo apt-get install -y git g++ libmpc-dev make flex
          curl -L -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${gcc_version}.tar.gz
          tar -zxf gcc-${gcc_version}.tar.gz
          rm gcc-${gcc_version}.tar.gz
          cd gcc-releases-gcc-${gcc_version}
          mkdir build
          cd build
          ../configure --disable-multilib
          (time make 2>/dev/null) 2>> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          du -sh .. >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log
          echo "end: $(date)" >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make.log

      - uses: actions/upload-artifact@v4
        with:
          name: gcc-12-3-0-make
          path: ${{ github.workspace }}/gcc-12-3-0-make.log

  gcc-12-3-0-make-j:
    runs-on: ubuntu-latest
    steps:
      - name: gcc 12.3.0 make -j$(nproc)
        run: |
          gcc_version='12.3.0'
          echo -e "\033[32m--------------- gcc-${gcc_version} make -j$(nproc) ---------------\033[0m" > ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo "start: $(date)" >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo "system info:" >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo pwd: $(pwd) >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo lscpu: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo core num: $(nproc) >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          lscpu >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo free -h: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          free -h >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo df -h: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo uname -a: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          uname -a >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo lsb_release -a: >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          lsb_release -a >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          sudo apt-get update
          sudo apt-get install -y git g++ libmpc-dev make flex
          curl -L -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${gcc_version}.tar.gz
          tar -zxf gcc-${gcc_version}.tar.gz
          rm gcc-${gcc_version}.tar.gz
          cd gcc-releases-gcc-${gcc_version}
          mkdir build
          cd build
          ../configure --disable-multilib
          (time make -j$(nproc) 2>/dev/null) 2>> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          du -sh .. >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log
          echo "end: $(date)" >> ${GITHUB_WORKSPACE}/gcc-12-3-0-make-j.log

      - uses: actions/upload-artifact@v4
        with:
          name: gcc-12-3-0-make-j
          path: ${{ github.workspace }}/gcc-12-3-0-make-j.log

  gcc-15-2-0-make:
    runs-on: ubuntu-latest
    steps:
      - name: gcc 15.2.0 make
        run: |
          gcc_version='15.2.0'
          echo -e "\033[32m--------------- gcc-${gcc_version} make ---------------\033[0m" > ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo "start: $(date)" >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo "system info:" >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo pwd: $(pwd) >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo lscpu: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo core num: $(nproc) >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          lscpu >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo free -h: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          free -h >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo df -h: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo uname -a: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          uname -a >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo lsb_release -a: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          lsb_release -a >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          sudo apt-get update
          sudo apt-get install -y git g++ libmpc-dev make flex
          curl -L -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${gcc_version}.tar.gz
          tar -zxf gcc-${gcc_version}.tar.gz
          rm gcc-${gcc_version}.tar.gz
          cd gcc-releases-gcc-${gcc_version}
          mkdir build
          cd build
          ../configure --disable-multilib
          (time make 2>/dev/null) 2>> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          du -sh .. >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log
          echo "end: $(date)" >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make.log

      - uses: actions/upload-artifact@v4
        with:
          name: gcc-15-2-0-make
          path: ${{ github.workspace }}/gcc-15-2-0-make.log

  gcc-15-2-0-make-j:
    needs: gcc-15-2-0-make
    runs-on: ubuntu-latest
    steps:
      - name: gcc release make -j$(nproc)
        run: |
          gcc_version='15.2.0'
          echo -e "\033[32m--------------- gcc-${gcc_version} make -j$(nproc) ---------------\033[0m" > ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo "start: $(date)" >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo "system info:" >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo pwd: $(pwd) >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo lscpu: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo core num: $(nproc) >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          lscpu >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo free -h: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          free -h >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo df -h: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo uname -a: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          uname -a >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo lsb_release -a: >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          lsb_release -a >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          sudo apt-get update
          sudo apt-get install -y git g++ libmpc-dev make flex
          curl -L -O https://github.com/gcc-mirror/gcc/archive/refs/tags/releases/gcc-${gcc_version}.tar.gz
          tar -zxf gcc-${gcc_version}.tar.gz
          rm gcc-${gcc_version}.tar.gz
          cd gcc-releases-gcc-${gcc_version}
          mkdir build
          cd build
          ../configure --disable-multilib
          (time make -j$(nproc) 2>/dev/null) 2>> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          du -sh .. >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          df -h >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log
          echo "end: $(date)" >> ${GITHUB_WORKSPACE}/gcc-15-2-0-make-j.log

      - uses: actions/upload-artifact@v4
        with:
          name: gcc-15-2-0-make-j
          path: ${{ github.workspace }}/gcc-15-2-0-make-j.log

  merge-logs:
    needs:
      # - gcc-master-make
      - gcc-master-make-j
      - gcc-12-3-0-make
      - gcc-12-3-0-make-j
      - gcc-15-2-0-make
      - gcc-15-2-0-make-j
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - name: merge logs
        run: |
          # cat gcc-master-make/gcc-master-make.log >> gcc-build-log.txt
          # echo >> gcc-build-log.txt
          cat gcc-master-make-j/gcc-master-make-j.log >> gcc-build-log.txt
          echo >> gcc-build-log.txt
          cat gcc-12-3-0-make/gcc-12-3-0-make.log >> gcc-build-log.txt
          echo >> gcc-build-log.txt
          cat gcc-12-3-0-make-j/gcc-12-3-0-make-j.log >> gcc-build-log.txt
          echo >> gcc-build-log.txt
          cat gcc-15-2-0-make/gcc-15-2-0-make.log >> gcc-build-log.txt
          echo >> gcc-build-log.txt
          cat gcc-15-2-0-make-j/gcc-15-2-0-make-j.log >> gcc-build-log.txt
          cat gcc-build-log.txt

      - uses: actions/upload-artifact@v4
        with:
          name: gcc-build-log
          path: gcc-build-log.txt
